services:
  neo4j:
    image: neo4j:4.4
    environment:
      NEO4J_AUTH: neo4j/password
      NEO4J_dbms_memory_heap_max__size: 2G
    ports:
      - "7474:7474" 
      - "7687:7687"  
    volumes:
      - neo4j_data:/data
    networks:
      - app_network

  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      NEO4J_URI: "bolt://neo4j:7687"
      NEO4J_USER: "neo4j"
      NEO4J_PASSWORD: "password"
    depends_on:
      - neo4j
    networks:
      - app_network

volumes:
  neo4j_data:

networks:
  app_network:
    driver: bridge