version: "3.8"

services:
  app:
    build: .
    ports:
      - 5000:5000
    volumes:
      - .:/app
    environment:
      FLASK_DEBUG: 1
      MONGO_URI: "mongodb://admin:admin@mongodb:27017/bilet12?authSource=admin"  # Полный URI с аутентификацией
    depends_on:
      mongodb:
        condition: service_healthy  # Ждем пока MongoDB будет готов
    command: flask run --host=0.0.0.0

  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: bilet12  # Явно указываем базу данных
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh -u admin -p admin --quiet
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  mongodb_data: