version: '3.8'

services:
  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      FLASK_APP: "app/__init__.py"
      FLASK_DEBUG: "1"
      NEO4J_URI: "bolt://neo4j:7687"  # Подключение к Neo4j внутри Docker
      NEO4J_USER: "neo4j"
      NEO4J_PASSWORD: "password123"  # Пароль, который установится при первом запуске
    depends_on:
      neo4j:
        condition: service_healthy
    command: ["flask", "run", "--host=0.0.0.0", "--port=5000"]
    restart: unless-stopped

  neo4j:
    image: neo4j:4.4
    ports:
      - "7474:7474"  # Neo4j Browser
      - "7687:7687"  # Bolt protocol (для подключения Python-драйвера)
    volumes:
      - neo4j_data:/data
      - ./neo4j.conf:/conf/neo4j.conf  # Монтируем конфигурационный файл (если у вас есть собственный)
    environment:
      NEO4J_AUTH: "neo4j/password123"
      NEO4J_server_config_strict_validation_enabled: "false"  # Отключение строгой проверки конфигурации
      NEO4J_dbms_security_auth_enabled: "false"  # Отключение аутентификации безопасности
      NEO4J_dbms_memory_heap_max_size: "2G"  # Установка максимального размера кучи памяти
      NEO4J_dbms_memory_pagecache_size: "1G"  # Установка размера кэширования страниц
    healthcheck:
      test: ["CMD", "cypher-shell", "-u", "neo4j", "-p", "password123", "RETURN 1"]

volumes:
  neo4j_data:
