services:
  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      FLASK_APP: "app/__init__.py"
      FLASK_DEBUG: "1"
      INFLUXDB_URL: "http://influxdb:8086"
      INFLUXDB_TOKEN: "my-admin-token"
      INFLUXDB_ORG: "my-org"
      INFLUXDB_BUCKET: "bilet15"
    depends_on:
      influxdb:
        condition: service_healthy
    command: ["sh", "-c", "while ! curl -s http://influxdb:8086/ping; do sleep 2; done; flask run --host=0.0.0.0 --port=5000"]
    restart: unless-stopped

  influxdb:
    image: influxdb:2.7
    ports:
      - "8086:8086"
    volumes:
      - influxdb_data:/var/lib/influxdb2
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: admin
      DOCKER_INFLUXDB_INIT_PASSWORD: admin123
      DOCKER_INFLUXDB_INIT_ORG: my-org
      DOCKER_INFLUXDB_INIT_BUCKET: bilet15
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: my-admin-token
    healthcheck:
      test: ["CMD", "influx", "ping"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  influxdb_data: