apiVersion: v1
kind: Service
metadata:
  name: django
spec:
  type: NodePort
  ports:
    - port: 8000         # Порт внутри кластера
      targetPort: 8000   # Порт на контейнере Django
      nodePort: 30080    # Порт, через который будет доступен сервис снаружи
  selector:
    app: django    

    